from typing import Optional, Protocol

from validator.common.types import (
    EpochAudit,
    Incident,
    MinerInfo,
    MinerVerificationState,
    QueryLog,
    VerificationResult,
)


class LogsSource(Protocol):
    """reads epoch data from registry and S3 (via manifest)"""

    async def fetch_finalized_epochs(self, limit: int = 20) -> Optional[list[dict]]: ...
    async def get_miner_configs(self, epoch_id: str) -> Optional[dict[str, dict]]: ...
    async def fetch_cu_allocations_from_manifest(
        self, manifest: dict
    ) -> dict[str, dict]: ...
    async def fetch_epoch_logs_from_manifest(
        self, manifest: dict, epoch_id: str
    ) -> list[QueryLog]: ...
    async def close(self) -> None: ...


class BlacklistService(Protocol):
    """checks and applies permanent bans"""

    async def is_blacklisted(self, coldkey: str) -> bool: ...
    async def ban(
        self,
        coldkey: str,
        hotkey: str,
        reason: str,
        epoch_id: str,
        evidence: dict,
    ) -> bool: ...
    async def get_banned_coldkeys(self) -> set[str]: ...
    async def close(self) -> None: ...


class EpochStore(Protocol):
    """write-only audit log for epoch results"""

    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def save_epoch_audit(self, audit: EpochAudit) -> None: ...
    async def is_epoch_processed(self, epoch_id: str) -> bool: ...
    async def mark_epoch_processed(
        self, epoch_id: str, weights_submitted: bool = False
    ) -> None: ...


class VerificationStore(Protocol):
    """stores verification-related state (results, incidents, etc)"""

    async def ensure_miner(self, hotkey: str, coldkey: str, uid: int) -> None: ...
    async def get_verification_state(
        self, miner_hotkey: str
    ) -> Optional[MinerVerificationState]: ...
    async def save_verification_state(self, state: MinerVerificationState) -> None: ...
    async def save_verification_result(
        self,
        result: VerificationResult,
        miner_hotkey: str,
        node_id: str,
        chain: str,
        epoch_id: str,
    ) -> None: ...
    async def save_incident(self, incident: Incident) -> None: ...
    async def increment_pass_count(self, miner_hotkey: str) -> None: ...
    async def increment_fail_count(self, miner_hotkey: str) -> None: ...


class ChainInterface(Protocol):
    """interaction with the bittensor chain"""

    async def get_current_block(self) -> int: ...
    async def get_tempo(self) -> int: ...
    async def set_weights(self, uids: list[int], weights: list[int]) -> bool: ...
    async def get_miners(self) -> list[MinerInfo]: ...
    def get_validator_hotkey(self) -> str: ...


class PriceSource(Protocol):
    """fetches alpha price and emissions"""

    async def get_alpha_price_usd(self) -> float: ...
    async def get_tao_price_usd(self) -> float: ...
    async def get_emissions_alpha(self) -> float: ...
    async def close(self) -> None: ...
